# Generated by Django 4.0.2 on 2022-02-23 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('calories', models.FloatField(null=True)),
                ('servings', models.FloatField(null=True)),
                ('fat', models.FloatField(null=True)),
                ('carb', models.FloatField(null=True)),
                ('protein', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('serving_amount', models.FloatField(null=True)),
                ('calories', models.FloatField(null=True)),
                ('fat', models.FloatField(null=True)),
                ('carb', models.FloatField(null=True)),
                ('protein', models.FloatField(null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('serving_size', models.IntegerField(null=True)),
                ('unit', models.CharField(max_length=200, null=True)),
                ('servings_per_container', models.FloatField(null=True)),
                ('calories', models.FloatField(null=True)),
                ('fat', models.FloatField(null=True)),
                ('carb', models.FloatField(null=True)),
                ('protein', models.FloatField(null=True)),
                ('tags', models.ManyToManyField(null=True, to='food.Tag')),
            ],
        ),
    ]
