# Generated by Django 4.0.2 on 2022-02-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_mealplan_day_alter_mealplan_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='day',
            field=models.DateField(null=True),
        ),
    ]
