# Generated by Django 4.0.2 on 2022-02-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_mealplan_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='day',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
