# Generated by Django 4.0.2 on 2022-02-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_mealplan_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='day',
            field=models.DateField(null=True),
        ),
    ]
