# Generated by Django 4.0.2 on 2022-02-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_mealplan_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealplan',
            old_name='day',
            new_name='date',
        ),
    ]
