# Generated by Django 4.0.2 on 2022-02-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_rename_day_mealplan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='day',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
