# Generated by Django 4.0.2 on 2022-02-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_mealplan_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='date_created',
        ),
        migrations.AddField(
            model_name='food',
            name='price_per_100cal',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='price_per_serving',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='price_per_100cal',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='price_per_serving',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='day',
            field=models.CharField(default=' ', max_length=10, null=True),
        ),
    ]
