# Generated by Django 4.0.2 on 2022-02-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_remove_food_date_created_food_price_per_100cal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
