# Generated by Django 4.0.2 on 2022-02-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_remove_member_date_created_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
